### ISSUE TITLE
/public/assets directory missing?

### ISSUE THREAD

**Issue by SaloniSonpal** [eguneys/voting_app#1]
Hi @eguneys , https://github.com/eguneys/voting_app/blob/master/app/views/layouts/main.hbs references /public/assets for stylesheets and scripts. Can you please share that as a part of your repo too?

**Comment by eguneys** [comment]
It is auto generated by gulp build, see https://github.com/eguneys/voting_app/blob/master/gulpfile.js#L35.

Though you can study this, it is an old project, I haven't updated it in a year.
